steps:
  - id: 'echo'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo ciao
  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '$_REGISTRY/kanboard:latest', 'docker/' ]
images: ['$_REGISTRY/kanboard:latest']