apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanboard
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "replatform-gke"
    networking.gke.io/managed-certificates: kanboard
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: "{{ ssl_domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kanboard
            port:
              number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kanboard
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 10
    type: HTTP
    requestPath: /ping.php
    port: 80