apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kanboard
  name: kanboard
  namespace: kanboard
spec:
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      serviceAccountName: kanboard
      containers:
      - image: {{kanboard_image}}:{{kanboard_tag}}
        imagePullPolicy: Always
        name: kanboard
        readinessProbe:
          httpGet:
            path: /ping.php
            port: 80
        livenessProbe:
          httpGet:
            path: /ping.php
            port: 80