apiVersion: v1
kind: Service
metadata:
  labels:
    app: kanboard
  name: kanboard
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "kanboard"}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: web
  selector:
    app: kanboard
  type: NodePort
